build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
    - DRONE_PYPI_PATH=testdata
    - DRONE_PYPI_REPOSITORY=http://localhost:8000
    - DRONE_PYPI_DISTRIBUTIONS=sdist
  commands:
    - apt-get update && apt-get install -y python-setuptools
    - go get
    - go build
    - go test -cover

compose:
  simplepypi:
    image: msteinert/simplepypi
    pull: true

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-pypi
    when:
      branch: master

plugin:
  name: Pypi
  desc: Publish a package to the Python package index.
  type: publish
  image: plugins/drone-pypi
  labels:
    - publish
    - python
