workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-docker

pipeline:
  build:
    image: golang:1.8
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
      - DRONE_PYPI_UPLOAD_PATH=testdata
      - DRONE_PYPI_REPOSITORY=http://localhost:8000
      - DRONE_PYPI_DISTRIBUTIONS=sdist
    commands:
      - apt-get update && apt-get install -y python-setuptools
      - go get .../.
      - go build
      - go test -cover

  publish:
    image: plugins/drone-docker
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-pypi
    when:
      branch: master

  plugin:
    name: Pypi
    desc: Publish a package to the Python package index.
    type: publish
    image: plugins/drone-pypi
    labels:
      - publish
      - python

services:
  simplepypi:
    image: msteinert/simplepypi
    pull: true
