workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-pypi

pipeline:
  build:
    image: golang:1.8
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
      - DRONE_PYPI_UPLOAD_PATH=testdata
      - DRONE_PYPI_REPOSITORY=http://localhost:8000
      - DRONE_PYPI_DISTRIBUTIONS=sdist
    commands:
      - apt-get update && apt-get install -y python-setuptools
      - go get .../.
      - go build
      - go test -cover

  publish:
    image: plugins/docker
    username: akalipetis
    password: ${DOCKER_PASS}
    repo: akalipetis/drone-pypi
    when:
      branch: intermediate
    tags: latest

services:
  simplepypi:
    image: msteinert/simplepypi
    pull: true
